ae_capstone_jmilaney:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ae-capstone-transformed
      dataset: dbt_jmilaney
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1

